PORT = 80
WS_URL = "ws"
DEBUG = True
LOGGERLEVEL = 10
FOLDERSCANWAITTIMEINMINUTES = 0.1
TEMPDIRECTORY = "neo4j_file_handling/temp/"
BACKUPDIRECTORY = "neo4j_file_handling/backup/"
LOGDIRECTORY = "neo4j_file_handling/logs/"
LOGFOLDER = "logs"
LOGFILE = "graphalyzer.log"
WEBSOCKETLOG = "websocket.log"
LOGLEVEL = 0 #All logs